In [1]:
from sqlalchemy import create_engine

In [2]:
postgres_user = 'dsbc_student'
postgres_pw = '7*.8G9QH21'
postgres_host = '142.93.121.174'
postgres_port = '5432'
postgres_db = 'dvdrentals'

engine = create_engine('postgresql://{}:{}@{}:{}/{}'.format(
    postgres_user, postgres_pw, postgres_host, postgres_port, postgres_db))

In [4]:
sql = '''
SELECT COUNT(*) AS count, rating
  FROM film f
  GROUP BY rating'''

results = engine.execute(sql)
engine.dispose()
rows = results.fetchall()

for row in rows:
  print(row)

(195, 'R')
(210, 'NC-17')
(194, 'PG')
(223, 'PG-13')
(178, 'G')

In [7]:
sql = '''
SELECT COUNT(*) AS count, rating, rental_duration
  FROM film f
  GROUP BY rating, rental_duration
  ORDER BY rental_duration'''

results = engine.execute(sql)
engine.dispose()
rows = results.fetchall()

for row in rows:
  print(row)

(37, 'NC-17', 3)
(42, 'R', 3)
(49, 'G', 3)
(39, 'PG-13', 3)
(36, 'PG', 3)
(28, 'G', 4)
(33, 'NC-17', 4)
(53, 'R', 4)
(48, 'PG-13', 4)
(41, 'PG', 4)
(42, 'PG-13', 5)
(33, 'G', 5)
(43, 'NC-17', 5)
(40, 'R', 5)
(33, 'PG', 5)
(50, 'PG-13', 6)
(27, 'R', 6)
(39, 'PG', 6)
(57, 'NC-17', 6)
(39, 'G', 6)
(29, 'G', 7)
(33, 'R', 7)
(40, 'NC-17', 7)
(44, 'PG-13', 7)
(45, 'PG', 7)

In [8]:
sql = '''
SELECT AVG(length)
  FROM film f
  GROUP BY length
  ORDER BY length'''

results = engine.execute(sql)
engine.dispose()
rows = results.fetchall()

for row in rows:
  print(row)

(Decimal('46.0000000000000000'),)
(Decimal('47.0000000000000000'),)
(Decimal('48.0000000000000000'),)
(Decimal('49.0000000000000000'),)
(Decimal('50.0000000000000000'),)
(Decimal('51.0000000000000000'),)
(Decimal('52.0000000000000000'),)
(Decimal('53.0000000000000000'),)
(Decimal('54.0000000000000000'),)
(Decimal('55.0000000000000000'),)
(Decimal('56.0000000000000000'),)
(Decimal('57.0000000000000000'),)
(Decimal('58.0000000000000000'),)
(Decimal('59.0000000000000000'),)
(Decimal('60.0000000000000000'),)
(Decimal('61.0000000000000000'),)
(Decimal('62.0000000000000000'),)
(Decimal('63.0000000000000000'),)
(Decimal('64.0000000000000000'),)
(Decimal('65.0000000000000000'),)
(Decimal('66.0000000000000000'),)
(Decimal('67.0000000000000000'),)
(Decimal('68.0000000000000000'),)
(Decimal('69.0000000000000000'),)
(Decimal('70.0000000000000000'),)
(Decimal('71.0000000000000000'),)
(Decimal('72.0000000000000000'),)
(Decimal('73.0000000000000000'),)
(Decimal('74.0000000000000000'),)
(Decimal('75.0000000000000000'),)
(Decimal('76.0000000000000000'),)
(Decimal('77.0000000000000000'),)
(Decimal('78.0000000000000000'),)
(Decimal('79.0000000000000000'),)
(Decimal('80.0000000000000000'),)
(Decimal('81.0000000000000000'),)
(Decimal('82.0000000000000000'),)
(Decimal('83.0000000000000000'),)
(Decimal('84.0000000000000000'),)
(Decimal('85.0000000000000000'),)
(Decimal('86.0000000000000000'),)
(Decimal('87.0000000000000000'),)
(Decimal('88.0000000000000000'),)
(Decimal('89.0000000000000000'),)
(Decimal('90.0000000000000000'),)
(Decimal('91.0000000000000000'),)
(Decimal('92.0000000000000000'),)
(Decimal('93.0000000000000000'),)
(Decimal('94.0000000000000000'),)
(Decimal('95.0000000000000000'),)
(Decimal('96.0000000000000000'),)
(Decimal('97.0000000000000000'),)
(Decimal('98.0000000000000000'),)
(Decimal('99.0000000000000000'),)
(Decimal('100.0000000000000000'),)
(Decimal('101.0000000000000000'),)
(Decimal('102.0000000000000000'),)
(Decimal('103.0000000000000000'),)
(Decimal('104.0000000000000000'),)
(Decimal('105.0000000000000000'),)
(Decimal('106.0000000000000000'),)
(Decimal('107.0000000000000000'),)
(Decimal('108.0000000000000000'),)
(Decimal('109.0000000000000000'),)
(Decimal('110.0000000000000000'),)
(Decimal('111.0000000000000000'),)
(Decimal('112.0000000000000000'),)
(Decimal('113.0000000000000000'),)
(Decimal('114.0000000000000000'),)
(Decimal('115.0000000000000000'),)
(Decimal('116.0000000000000000'),)
(Decimal('117.0000000000000000'),)
(Decimal('118.0000000000000000'),)
(Decimal('119.0000000000000000'),)
(Decimal('120.0000000000000000'),)
(Decimal('121.0000000000000000'),)
(Decimal('122.0000000000000000'),)
(Decimal('123.0000000000000000'),)
(Decimal('124.0000000000000000'),)
(Decimal('125.0000000000000000'),)
(Decimal('126.0000000000000000'),)
(Decimal('127.0000000000000000'),)
(Decimal('128.0000000000000000'),)
(Decimal('129.0000000000000000'),)
(Decimal('130.0000000000000000'),)
(Decimal('131.0000000000000000'),)
(Decimal('132.0000000000000000'),)
(Decimal('133.0000000000000000'),)
(Decimal('134.0000000000000000'),)
(Decimal('135.0000000000000000'),)
(Decimal('136.0000000000000000'),)
(Decimal('137.0000000000000000'),)
(Decimal('138.0000000000000000'),)
(Decimal('139.0000000000000000'),)
(Decimal('140.0000000000000000'),)
(Decimal('141.0000000000000000'),)
(Decimal('142.0000000000000000'),)
(Decimal('143.0000000000000000'),)
(Decimal('144.0000000000000000'),)
(Decimal('145.0000000000000000'),)
(Decimal('146.0000000000000000'),)
(Decimal('147.0000000000000000'),)
(Decimal('148.0000000000000000'),)
(Decimal('149.0000000000000000'),)
(Decimal('150.0000000000000000'),)
(Decimal('151.0000000000000000'),)
(Decimal('152.0000000000000000'),)
(Decimal('153.0000000000000000'),)
(Decimal('154.0000000000000000'),)
(Decimal('155.0000000000000000'),)
(Decimal('156.0000000000000000'),)
(Decimal('157.0000000000000000'),)
(Decimal('158.0000000000000000'),)
(Decimal('159.0000000000000000'),)
(Decimal('160.0000000000000000'),)
(Decimal('161.0000000000000000'),)
(Decimal('162.0000000000000000'),)
(Decimal('163.0000000000000000'),)
(Decimal('164.0000000000000000'),)
(Decimal('165.0000000000000000'),)
(Decimal('166.0000000000000000'),)
(Decimal('167.0000000000000000'),)
(Decimal('168.0000000000000000'),)
(Decimal('169.0000000000000000'),)
(Decimal('170.0000000000000000'),)
(Decimal('171.0000000000000000'),)
(Decimal('172.0000000000000000'),)
(Decimal('173.0000000000000000'),)
(Decimal('174.0000000000000000'),)
(Decimal('175.0000000000000000'),)
(Decimal('176.0000000000000000'),)
(Decimal('177.0000000000000000'),)
(Decimal('178.0000000000000000'),)
(Decimal('179.0000000000000000'),)
(Decimal('180.0000000000000000'),)
(Decimal('181.0000000000000000'),)
(Decimal('182.0000000000000000'),)
(Decimal('183.0000000000000000'),)
(Decimal('184.0000000000000000'),)
(Decimal('185.0000000000000000'),)

In [ ]:
sql = '''
SELECT AVG(length)
  FROM film f
  GROUP BY length
  ORDER BY length'''

results = engine.execute(sql)
engine.dispose()
rows = results.fetchall()

for row in rows:
  print(row)

In [ ]:
Calculate the standard deviation of the movie lengths. Calculate this by defining a function.